name: "gsplat_vanilla"
tag: ""
exp_root_dir: "outputs"
seed: 0
description: ""

data_type: "colmap"
data: 
  source_path: '/mnt/d/data/GaussianData/carla_sample'
  eval: False
  data_device: 'cuda'
  resolution: -1
  images: 'images'
  model_path: ''
  shuffle: True
system_type: "vanilla-gsplat"
system: 
  representation_type: "gaussian-model"
  representation:
    max_sh_degree: 3
  trainer_type: "gaussian-trainer"
  trainer:
    detect_anomaly: False
    iterations: 30000
    start_checkpoint: None
    save_iterations: [7000, 30000]
    test_iterations: [7000, 30000]
    ckpt_iterations: []
  paramOptim_type: "adam+customLR-paramOptim"
  paramOptim:
    position_lr_delay_mult: 0.01
    position_lr_final: 1.6e-06
    position_lr_init: 0.00016
    position_lr_max_steps: 30000
    feature_lr: 0.0025
    rotation_lr: 0.001
    scaling_lr: 0.005
    opacity_lr: 0.05
  structOptim_type: "split.clone.prune-structOptim"
  structOptim:
    max_sh_drgree: 3
    percent_dense: 0.01
    opacity_reset_interval: 3000
    densify_from_iter: 500
    densify_until_iter: 15000
    densify_grad_threshold: 0.0002
    densification_interval: 100
    size_threshold: 20
    min_opacity: 0.005
    num_split: 2
  loss_type: "l1+ssim-loss"
  loss:
    lambda_dssim: 0.2
  renderer_type: "diffRasterizer-renderer"
  renderer:
    background_color: [0,0,0]
    debug: False
    compute_cov3D_python: False
    convert_SHs_python: False
    scaling_modifier: 1.0
    prefiltered: False
    override_color: [-1,-1,-1]
  
checkpoint:
  Nothing: ""

logger:
  version: 1
  disable_existing_loggers: False
  formatters:
    datetime:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    simple:
      format: "%(message)s"
  handlers:
    console:
      class: "logging.StreamHandler"
      formatter: "simple"
      level: "DEBUG"
      stream: "ext://sys.stdout"
    info_file_handler:
      backupCount: 20
      class: "logging.handlers.RotatingFileHandler"
      encoding: "utf8"
      filename: "info.log"
      formatter: "datetime"
      level: "INFO"
      maxBytes: 10485760
  root:
    handlers:
    - "console"
    - "info_file_handler"
    level: "INFO"
  
  